### ISSUE TITLE
example doesn't print outputs correctly

### ISSUE THREAD

**Issue by ndimhypervol** [thomasp85/shinyFiles#22] opened 2015-06-18 19:21 UTC
I just downloaded your package and ran the example and noticed that the renderPrints aren't rendering when I make my selections.

**Comment by thomasp85** [comment] 2015-06-19 06:39
Duplicate of #21. Update Shiny with latest version from GitHub, as it is a bug in that package...

**Closed by thomasp85** 2015-06-19 06:39 UTC
Labels: duplicate
