### ISSUE TITLE
UI is not displayed properly in the latest Boostrap4-based bs4Dash package

### ISSUE THREAD

**Issue by jnhyeon** [thomasp85/shinyFiles#158] opened 2021-06-29 23:54 UTC
Thank you for making such a wonderful package.
Your package works fine with Bootstarp3 based shinydashboard, shinydashboardplus packages.
However, the UI is not displayed properly in the latest Boostrap4-based bs4Dash package.
I hope your package also works well with the bs4Dash package.

Thank you.

**Comment by vnijs** [comment] 2021-06-30 07:05
Can you try out the development version? Alignment should look a little better at least. If you see problems please provide screenshots. The dropdown buttons do not work in bs4. I asked the developer of bslib for any suggestions (see issue linked below).

https://github.com/rstudio/bslib/issues/347

**Comment by jnhyeon** [comment] 2021-06-30 07:53
Thank you for the reply.
I installed the developer version (0.9.0.90000) with devtools::install_github('thomasp85/shinyFiles').
However, the UI of shinyDirButton is still not displayed properly in bs4Dash.
'Contents' is under 'Directories'.
Thank you.

![image](https://user-images.githubusercontent.com/3360511/123922956-80577f00-d9c3-11eb-90d3-ad9de5fd70a5.png)

**Comment by vnijs** [comment] 2021-06-30 08:15
I have not use b4dash. Only bslib. Can you provide a minimal reproducible example?

**Comment by vnijs** [comment] 2021-07-01 00:55
Thanks @jnhyeon. With the help of @cpsievert I think I have most of the changes address. However, **not** the issue why these windows are no longer shown in-line as they were before. Perhaps @thomasp85 has some ideas?

**Comment by ruthkr** [comment] 2021-07-04 17:55
Hi, @vnijs I think I've found a fix for the element distribution in the modal in Bootstrap 4 using {bslib} (and presumedly {bs4Dash}). I've just added the following to my to my CSS stylesheet, and everything looks correctly aligned in the modal:
```css
.sF-dirWindow {
  display: flex;
}

.sF-breadcrumps {
  width: calc(100% - 380px) !important;
}
```

![image](https://user-images.githubusercontent.com/38610118/124394854-1c9dc080-dcf9-11eb-82ba-cb39033a31c3.png)

**Comment by vnijs** [comment] 2021-07-04 20:39
Thank you @ruthkr! That was very helpful. Please try out the latest [commit](https://github.com/thomasp85/shinyFiles/commit/1ae4ef63ef32164cdabcb28e86a6ae0b07ce733e)

**Comment by jnhyeon** [comment] 2021-07-04 23:24
Thanks to @vnijs and @ruthkr.
I can finally upgrade my company project from shinydashboardplus package to bs4Dash package.

Thank you very much. :)

**Comment by vnijs** [comment] 2021-11-06 22:06
Closing. Pushing new version to CRAN soon

**Closed by vnijs** 2021-11-06 22:06 UTC

**Comment by ShinyFabio** [comment] 2022-03-31 10:41
Hi, this problem persists if I use a `{fresh}` theme inside bs4Dash package. Here's a reproducible example:

```
library(shiny)
library(bs4Dash)
library(shinyFiles) # devtools::install_github('thomasp85/shinyFiles')
library(fresh)


ui <- dashboardPage(
  dashboardHeader(title = "Basic dashboard",skin = "light", status = "primary"),
  dashboardSidebar(skin = "light"),
  dashboardBody(

    fresh::use_theme(
      fresh::create_theme(
        fresh::bs4dash_vars(navbar_light_color = "#2c2f76")
      )
    ),
    
    fluidRow(
      box(width = 12,
          fluidRow(
            column(6,
                   shinyFilesButton("file", "File select", "Please select a file",
                                    multiple = FALSE)
            ),
            column(6,
                   shinyDirButton("directory", "Folder select", "Please select a folder")
            )
          )
      )
    )
  )
)

server <- function(input, output, session) {
  volumes <- c(Home = fs::path_home(), getVolumes()())
  
  shinyFileChoose(input, "file", roots = volumes, session = session)
  
  shinyDirChoose(input, "directory", roots = volumes, session = session)
}

shinyApp(ui, server)
```

**Comment by vnijs** [comment] 2022-04-01 04:03
Not sure what the issue but I can't even get the buttons to work in this demo, presumably, due to a conflict with bs4Dash. `shinyFiles` works as expected with the Rstudio-supproted `bslib`. If you supply a PR with a fix that would make this work with bs4Dash as well I would be happy to review.

![image](https://user-images.githubusercontent.com/2998956/161192516-0d7beda6-db06-4a3a-afea-7c22c102dead.png)

**Comment by ShinyFabio** [comment] 2022-04-01 07:26
Exactly, it doesn't open anything. I don't have your devtools error. I just took the previous example from [jnhyeon](https://github.com/jnhyeon) and added the `fresh` theme.  As you can see it seems that everything is rendered but not displayed.

![Screenshot (231)](https://user-images.githubusercontent.com/78078351/161215582-2940965d-e758-4b75-86ef-e0e0ffd08f0e.png)

However what is a PR? I'm sorry I'm not English.

**Comment by vnijs** [comment] 2022-04-05 05:52
A PR is a "Pull Request". It is a suggested fix for the problem that you are seeing. shinyFiles works as intended with `bslib` which is supported by Rstudio and offers access to bootstrap 3 and 4. It would be nice if everything worked with other libraries as well that is not something that I can currently carve out time for if it is not working. Sorry

**Comment by ShinyFabio** [comment] 2022-04-05 07:27
Ah ok now I understood. I can have a look but I'm not very skilled

**Comment by vojtam** [comment] 2023-02-04 14:26
@ShinyFabio I had the same problem. The solution I found is to add this line to my CSS stylesheet. 
```css
.fade:not(.show) {
  opacity: 1; !important
}
```

**Comment by vnijs** [comment] 2023-02-05 03:46
@vojtam Thanks. What does this do exactly?

**Comment by vojtam** [comment] 2023-02-23 09:25
I had the same problem where sf dialog window wasn't visible when using bs4Dash. Digging through developer tools revealed that this CSS class set the opacity to 0, leaving the modal window invisible. Adding the above rule to my stylesheet solved the problem. I'm aware that using !important should be avoided.
