### ISSUE TITLE
shinythemes not supported

### ISSUE THREAD

**Issue by caleblareau** [thomasp85/shinyFiles#32] opened 2016-05-05 02:32 UTC
I had an issue trying to have both a theme and i/o with shinyFiles. MWE is the shinyFilesExample() with a theme added

library(shinythemes)
https://rstudio.github.io/shinythemes/

When I go to browse a file with any of the buttons, the screen gets grey-ed out and I can't navigate/select.

Thanks!

**Comment by ZdenekKabat** [comment] 2016-08-24 13:04
Confirmed. It would be nice to have shinythemes compatibility.

**Comment by thomasp85** [comment] 2016-08-24 13:08
shinyFiles relies heavily on bootstrap v3. If the themes in shinythemes are build on top of that there should be no problem, but otherwise it is out of scope to support random css specs... I would guess that the problem is that some of the themes are based on bootstrap v2?

**Comment by ZdenekKabat** [comment] 2016-08-24 13:16
I cannot tell, but it seems that the last update of shinythemes was 2 years ago. The .css files have comments including "bootswatch v3.3.1+2" so I'm not sure.

**Closed** 2016-08-28 15:55 UTC
